apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orderService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.orderService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orderService.name }}
    spec:
      containers:
      - name: user
        image: {{ .Values.orderService.image }}
        ports:
        - containerPort: {{ .Values.orderService.port }}
